# BEGIN COPYRIGHT BLOCK
# (C) 2018 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

services:
  - docker

env:
  - FEDORA=27
  - FEDORA=28

install:
  - docker pull registry.fedoraproject.org/fedora:$FEDORA
  - docker run
      --name=container
      --detach
      -i
      -v $(pwd):/root/nuxwdog
      registry.fedoraproject.org/fedora:$FEDORA
  - docker exec container dnf install -y dnf-plugins-core make rpm-build
  - docker exec container dnf builddep -y --spec /root/nuxwdog/nuxwdog.spec
  - docker exec container /root/nuxwdog/build_nuxwdog

script:
- docker exec container rpm -ivh /root/nuxwdog/release/dist/rpmpkg/RPMS/x86_64/*